# Rename this file to secrets.yml and do not check into repository
defaults: &defaults
  secret_key_base: '' # rake secret || SecureRandom.hex(64)

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  google_analytics_id: ''

